import type { Metadata } from 'next';

import FullscreenDesktop from '@/components/ad/FullscreenDesktop';
import FullscreenMobile from '@/components/ad/FullscreenMobile';
import MailRu from '@/components/counters/MailRu';
import YandexMetrika from '@/components/counters/YandexMetrika';

import { MapProvider } from '@/providers/MapProvider';

//@ts-ignore
import '@/styles/global.scss';

export const metadata: Metadata = {
	title: 'MOSMAP | Геоаналитика',
	description: 'Generated by create next app',
	icons: {
		icon: '/images/icons/logo_mini.svg',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<MapProvider>
				<body>
					<YandexMetrika />
					<MailRu />

					<script>window.yaContextCb=window.yaContextCb||[]</script>
					<script src='https://yandex.ru/ads/system/context.js' async></script>

					<FullscreenDesktop />
					<FullscreenMobile />
					{children}
				</body>
			</MapProvider>
		</html>
	);
}
