import type { Metadata } from 'next';

import { MapProvider } from '@/providers/MapProvider';

//@ts-ignore
import '@/styles/global.scss';

export const metadata: Metadata = {
	title: 'MOSMAP | Геоаналитика',
	description: 'Generated by create next app',
	icons: {
		icon: '/images/icons/logo_mini.svg',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<MapProvider>
				<body>{children}</body>
			</MapProvider>
		</html>
	);
}
